# Setup
title:            'State Chief Data Officers Network'
tagline:          'Data Policy Options'
description:      'State Data Policy Playbook'

author:
  name:           'State Chief Data Officers Network'
  url:            https://github.com/CTOpenData/data-sharing-playbook

# Custom vars
version:          1.0.0

github:
  repo:           

# Google Analytics
google_analytics: 
